In [1]:
import pandas as pd
from RFEClassification import kBest

In [2]:
dataset1=pd.read_csv("prep.csv",index_col=None)

In [3]:
df2=dataset1

df2 = pd.get_dummies(df2, drop_first=True)

indep_X=df2.drop('classification_yes', axis=1)
dep_y=df2['classification_yes']

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [17]:
kbest=kBest.rfeFeature(indep_X,dep_y,6)       
rfelist = kbest
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [18]:
for i in rfelist:
    X_train, X_test, y_train, y_test=kBest.split_scalar(kbest[0],dep_y)
    classifier,Accuracy,report,X_test,y_test,cm=kBest.logistic(X_train,y_train,X_test,y_test)
    acclog.append(Accuracy)

    classifier,Accuracy,report,X_test,y_test,cm=kBest.svm_linear(X_train,y_train,X_test,y_test)  
    accsvml.append(Accuracy)
    
    classifier,Accuracy,report,X_test,y_test,cm=kBest.svm_NL(X_train,y_train,X_test,y_test)  
    accsvmnl.append(Accuracy)
        
    classifier,Accuracy,report,X_test,y_test,cm=kBest.knn(X_train,y_train,X_test,y_test)  
    accknn.append(Accuracy)
        
    classifier,Accuracy,report,X_test,y_test,cm=kBest.Navie(X_train,y_train,X_test,y_test)  
    accnav.append(Accuracy)
        
    classifier,Accuracy,report,X_test,y_test,cm=kBest.Decision(X_train,y_train,X_test,y_test)  
    accdes.append(Accuracy)
        
    classifier,Accuracy,report,X_test,y_test,cm=kBest.random(X_train,y_train,X_test,y_test)  
    accrf.append(Accuracy)

In [19]:
result=kBest.rfe_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [8]:
#5
result

             Logistic  SVMl SVMnl   KNN Navie Decision Random
Logistic         0.98  0.98  0.98  0.98  0.98     0.98   0.98
SVC              0.98  0.98  0.98  0.98  0.98     0.98   0.98
DecisionTree     0.98  0.98  0.98  0.98  0.98     0.98   0.98
RandomForest     0.98  0.98  0.98  0.98  0.98     0.98   0.98

In [12]:
#3
result

             Logistic  SVMl SVMnl   KNN Navie Decision Random
Logistic         0.94  0.94  0.94  0.94  0.94     0.94   0.94
SVC              0.94  0.94  0.94  0.94  0.94     0.94   0.94
DecisionTree     0.94  0.94  0.94  0.94  0.94     0.94   0.94
RandomForest     0.94  0.94  0.94  0.94  0.94     0.94   0.94

In [16]:
#4
result

             Logistic  SVMl SVMnl   KNN Navie Decision Random
Logistic         0.95  0.95  0.95  0.95  0.95     0.95   0.95
SVC              0.95  0.95  0.95  0.95  0.95     0.95   0.95
DecisionTree     0.95  0.95  0.95  0.95  0.95     0.95   0.95
RandomForest     0.95  0.95  0.95  0.95  0.95     0.95   0.95

In [20]:
#6
result

             Logistic  SVMl SVMnl   KNN Navie Decision Random
Logistic         0.98  0.98  0.98  0.98  0.98     0.99   0.98
SVC              0.98  0.98  0.98  0.98  0.98     0.99   0.98
DecisionTree     0.98  0.98  0.98  0.98  0.98     0.99   0.98
RandomForest     0.98  0.98  0.98  0.98  0.98     0.99   0.98