In [1]:
import pandas as pd

In [2]:
dataset1=pd.read_csv("prep.csv",index_col=None)
df2=dataset1
df2 = pd.get_dummies(df2, drop_first=True)

indep_X=df2.drop('classification_yes', axis=1)
dep_Y=df2['classification_yes']

In [14]:
from RFERegression import rfeRegression
rfelist=rfeRegression.rfeFeature(indep_X,dep_Y,5)       
acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

In [15]:
for i in rfelist:   
    X_train, X_test, y_train, y_test=rfeRegression.split_scalar(i,dep_Y)  
    r2_lin=rfeRegression.Linear(X_train,y_train,X_test,y_test)
    acclin.append(r2_lin)
    
    r2_sl=rfeRegression.svm_linear(X_train,y_train,X_test,y_test)    
    accsvml.append(r2_sl)
    
    r2_NL=rfeRegression.svm_NL(X_train,y_train,X_test,y_test)
    accsvmnl.append(r2_NL)
    
    r2_d=rfeRegression.Decision(X_train,y_train,X_test,y_test)
    accdes.append(r2_d)
    
    r2_r=rfeRegression.random(X_train,y_train,X_test,y_test)
    accrf.append(r2_r)

In [16]:
import warnings
warnings.filterwarnings('ignore')

In [17]:
result=rfeRegression.rfe_regression(acclin,accsvml,accdes,accrf)

In [6]:
#3
result

                Linear      SVMl  Decision    Random
Linear        0.441961  0.262153  0.441961  0.441816
SVC           0.441961  0.262153  0.441961  0.441816
Random        0.664893  0.609652  0.965961  0.916304
DecisionTree  0.676174  0.670691  0.933504  0.887256

In [13]:
#4
result

                Linear      SVMl  Decision    Random
Linear         0.60401  0.457046  0.776711  0.776492
SVC            0.60401  0.457046  0.776711  0.776492
Random        0.671727  0.628963  0.835247    0.8403
DecisionTree  0.681563  0.614992   0.96711  0.923559

In [18]:
#5
result

                Linear      SVMl  Decision    Random
Linear        0.620124  0.457136   0.77924  0.780135
SVC           0.604508  0.456871  0.776474  0.776745
Random        0.674403  0.628206  0.696181  0.815538
DecisionTree  0.686361  0.643365  0.836806  0.845303